###
GET http://localhost:3000/users
### 

POST http://localhost:3000/users
Content-Type: application/json

{
  "email" : "ello23@gmail.com",
  "firstName" : "길동",
  "lastName": "홍",
  "address" : "영등포"
}

###
GET http://localhost:3000/users/32648539-1c02-4705-a057-f536aa6f5635

###
PATCH http://localhost:3000/users/32648539-1c02-4705-a057-f536aa6f5635
Content-Type: application/json

{
  "lastName" : "Lee"
}

###
DELETE http://localhost:3000/users/32648539-1c02-4705-a057-f536aa6f5635